version: '3'

networks:
    webapps:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "8009:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw

        depends_on:
            - php
            - postgres
        networks:
            - webapps

    php:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: ${APP_NAME}

        volumes:
            - ./:/var/www/html
        ports:
            - "9009:9000"
        networks:
            - webapps

    postgres:
        image: postgres:16.4-alpine
        container_name: ${APP_NAME}_db
        restart: unless-stopped
        ports:
            - "5449:5432"
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data

        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"

        networks:
            - webapps
